# Generated by Django 5.0.4 on 2024-04-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(db_index=True, max_length=17, unique=True)),
                ('invite_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('activated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_by', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
